#pragma once

#include <stdint.h>

uint32_t weft_regs(void);
char*    weft_emit_loop(char* buf, char* label);

typedef char* weft_emit_fn(char* buf, int[], int[], int[], int[], int64_t);

weft_emit_fn
    weft_emit_splat_8,
    weft_emit_uniform_8,
    weft_emit_load_8,
    weft_emit_store_8,
    weft_emit_assert_8,

    weft_emit_splat_16,
    weft_emit_uniform_16,
    weft_emit_load_16,
    weft_emit_store_16,
    weft_emit_assert_16,

    weft_emit_splat_32,
    weft_emit_uniform_32,
    weft_emit_load_32,
    weft_emit_store_32,
    weft_emit_assert_32,

    weft_emit_splat_64,
    weft_emit_uniform_64,
    weft_emit_load_64,
    weft_emit_store_64,
    weft_emit_assert_64,

    weft_emit_not_8,
    weft_emit_and_8,
    weft_emit_bic_8,
    weft_emit_or_8,
    weft_emit_xor_8,
    weft_emit_sel_8,
    weft_emit_shli_i8,
    weft_emit_shri_s8,
    weft_emit_shri_u8,
    weft_emit_shlv_i8,
    weft_emit_shrv_s8,
    weft_emit_shrv_u8,
    weft_emit_add_i8,
    weft_emit_sub_i8,
    weft_emit_mul_i8,
    weft_emit_eq_i8,
    weft_emit_lt_s8,
    weft_emit_lt_u8,
    weft_emit_le_s8,
    weft_emit_le_u8,

    weft_emit_not_16,
    weft_emit_and_16,
    weft_emit_bic_16,
    weft_emit_or_16,
    weft_emit_xor_16,
    weft_emit_sel_16,
    weft_emit_shli_i16,
    weft_emit_shri_s16,
    weft_emit_shri_u16,
    weft_emit_shlv_i16,
    weft_emit_shrv_s16,
    weft_emit_shrv_u16,
    weft_emit_add_i16,
    weft_emit_sub_i16,
    weft_emit_mul_i16,
    weft_emit_eq_i16,
    weft_emit_lt_s16,
    weft_emit_lt_u16,
    weft_emit_le_s16,
    weft_emit_le_u16,

    weft_emit_cast_f16,
    weft_emit_cast_s16,
    weft_emit_ceil_f16,
    weft_emit_floor_f16,
    weft_emit_sqrt_f16,
    weft_emit_add_f16,
    weft_emit_sub_f16,
    weft_emit_mul_f16,
    weft_emit_div_f16,
    weft_emit_eq_f16,
    weft_emit_lt_f16,
    weft_emit_le_f16,

    weft_emit_not_32,
    weft_emit_and_32,
    weft_emit_bic_32,
    weft_emit_or_32,
    weft_emit_xor_32,
    weft_emit_sel_32,
    weft_emit_shli_i32,
    weft_emit_shri_s32,
    weft_emit_shri_u32,
    weft_emit_shlv_i32,
    weft_emit_shrv_s32,
    weft_emit_shrv_u32,
    weft_emit_add_i32,
    weft_emit_sub_i32,
    weft_emit_mul_i32,
    weft_emit_eq_i32,
    weft_emit_lt_s32,
    weft_emit_lt_u32,
    weft_emit_le_s32,
    weft_emit_le_u32,

    weft_emit_cast_f32,
    weft_emit_cast_s32,
    weft_emit_ceil_f32,
    weft_emit_floor_f32,
    weft_emit_sqrt_f32,
    weft_emit_add_f32,
    weft_emit_sub_f32,
    weft_emit_mul_f32,
    weft_emit_div_f32,
    weft_emit_eq_f32,
    weft_emit_lt_f32,
    weft_emit_le_f32,

    weft_emit_not_64,
    weft_emit_and_64,
    weft_emit_bic_64,
    weft_emit_or_64,
    weft_emit_xor_64,
    weft_emit_sel_64,
    weft_emit_shli_i64,
    weft_emit_shri_s64,
    weft_emit_shri_u64,
    weft_emit_shlv_i64,
    weft_emit_shrv_s64,
    weft_emit_shrv_u64,
    weft_emit_add_i64,
    weft_emit_sub_i64,
    weft_emit_mul_i64,
    weft_emit_eq_i64,
    weft_emit_lt_s64,
    weft_emit_lt_u64,
    weft_emit_le_s64,
    weft_emit_le_u64,

    weft_emit_cast_f64,
    weft_emit_cast_s64,
    weft_emit_ceil_f64,
    weft_emit_floor_f64,
    weft_emit_sqrt_f64,
    weft_emit_add_f64,
    weft_emit_sub_f64,
    weft_emit_mul_f64,
    weft_emit_div_f64,
    weft_emit_eq_f64,
    weft_emit_lt_f64,
    weft_emit_le_f64,

    weft_emit_narrow_i16,
    weft_emit_narrow_i32,
    weft_emit_narrow_i64,
    weft_emit_narrow_f32,
    weft_emit_narrow_f64,
    weft_emit_widen_s8,
    weft_emit_widen_s16,
    weft_emit_widen_s32,
    weft_emit_widen_u8,
    weft_emit_widen_u16,
    weft_emit_widen_u32,
    weft_emit_widen_f16,
    weft_emit_widen_f32;
